### ISSUE TITLE
Change -l to use "original" line numbers for csvgrep ?

### ISSUE THREAD

**Issue by JoeGermuska** [onyxfish/csvkit#155]
I was surprised by the behavior of csvgrep -l -- the lines are numbered from 1 to N consecutively based on the post-grep output. I was kind of expecting to see the original line numbers.

This would be a backwards-incompatible change, in a sense, so not sure how you want to handle it.

**Comment by jpmckinney** [comment]
I think we can add the line numbers with the reader, and adjust the `column_ids` appropriately.
