### ISSUE TITLE
Sniffing behavior not consistent across tools

### ISSUE THREAD

**Issue by onyxfish** [onyxfish/csvkit#166]
Table.from_csv sniffs and then applies keyword args, all other tools do not sniff.

**Comment by jpmckinney** [comment]
I've linked a few issues that all suggest that CSV sniffing is error-prone (and slow), producing subtle bugs, where most people won't realize that CSV sniffing is the issue. I propose making sniffing "opt-in".

**Comment by onyxfish** [comment]
Hmmm, I'm on the fence about this. We're only seeing the negative case: where it doesn't work and not the value created by having it "just work", which I suspect it does in the majority of cases.

**Comment by onyxfish** [comment]
Also, just to add to that, right now the issue is that the problem is the sniff limit and that isn't obvious, but if we're dealing with all the ways the parsing can going wrong if the dialect isn't specified, that's can also cause a lot of equally opaque errors.

**Comment by jpmckinney** [comment]
Yeah, seems like there'll be many issues related to this either way - and we don't want to sniff the entire file. Should we add a troubleshooting section with something along the lines of "try it again with `--snifflimit 0`"?

**Comment by onyxfish** [comment]
Yeah, I think that sounds like a good middle-ground. I'm always a fan of turning hard code problems into easy documentation problems.

**Comment by evz** [comment]
FWIW, as a guy who saw this in #252 I'm pretty OK with this being added to a troubleshooting section in the documentation. Thanks for helping straighten this out.

**Comment by jpmckinney** [comment]
I've added snifflimit and no-inference support to all tools except csvjoin. Closing in favor of #571 - assuming I've understood the scope of this issue. Docs were also added to tricks.rst.
