### ISSUE TITLE
csvstat's functionality does not seem to be available as a library

### ISSUE THREAD

**Issue by mk270** [onyxfish/csvkit#184]

**Comment by jpmckinney** [comment]
I believe this is closed by https://github.com/onyxfish/agate-stats

**Comment by onyxfish** [comment]
Just going to chime in here to say that [agate](http://agate.readthedocs.org) is the "programmable csvkit". So yes, we definitely won't be fixing this in csvkit itself.

**Comment by mk270** [comment]
well, thanks for the update, anyway
