### ISSUE TITLE
testxls_converted.csv and testxlsx_converted.csv should be equivalent

### ISSUE THREAD

**Issue by billwanjohi** [onyxfish/csvkit#211]
The xls and xlsx example workbooks have equivalent data. We should make the expected output of their conversion identical. Or better, just test against the same csv.

The current differences:

*   last column gets a placeholder name ('_unnamed') for xls, but not xlsx
*   value of 1 represented as '1.0' and '1' in xls and xlsx respectively
*   '1920-01-01T00:00:00' datetime represented as '1920-01-01' for xlsx

**Comment by jpmckinney** [comment]
Superseded by #507?

**Comment by jpmckinney** [comment]
XLS and XLSX fils may look the same when rendered in Excel, but they are not the same at the serialization level. See #507.
