### ISSUE TITLE
in2csv should create [filename]_1.csv, [filename]_2.csv for multi-sheet XLS/XLSX input

### ISSUE THREAD

**Issue by axfelix** [onyxfish/csvkit#217]
should be self-explanatory from issue name. can currently specify which sheet you want converted, but oftentimes it's more productive to just dump them all, especially when the number of sheets isn't known without user intermediation.

**Comment by hydrosquall** [comment]
bumping this as something that would be helpful :)

**Comment by megahall** [comment]
I ran into this also. It would be cool if there were a way to specify the sheet index, from 0 to X, as a command-line options.

**Comment by jpmckinney** [comment]
Dup #251, Fixed #473

**Comment by axfelix** [comment]
hey, thanks!

**Comment by hydrosquall** [comment]
much appreciated!
