### ISSUE TITLE
in2csv converts 0 to empty string in .xls

### ISSUE THREAD

**Issue by mikejcorey** [onyxfish/csvkit#225]
When running in2csv on an XLS file, 0s were converted to empty strings.

Initially I thought it could be because it was the last column, but it happens in any column. I also tried running with the --no-inference flag, with the same result.

Sample data here:
http://static.apps.cironline.org/misc/in2csvproblem.xls

This was on Ubuntu Raring.

**Comment by jpmckinney** [comment]
Can reproduce.

**Comment by onyxfish** [comment]
Sounds like I've got a `if not` instead of an `if is None`. Did you test this against the agate-excel version? If so should probably file a bug there and reference from here.

**Comment by jpmckinney** [comment]
If that version is on master, then master has this issue.

    in2csv in2csvproblem.xls

Look at the last column of the first row with "DETECTED". It should end with a 0.

**Comment by onyxfish** [comment]
Very curious. Cross-filed to https://github.com/onyxfish/agate-excel/issues/3

**Comment by onyxfish** [comment]
I can't replicate this with agate 1.2.2 and the latest master of agate-excel, which I'm about to push to a release. I must have fixed it, though I'm not sure if it was a problem with agate-excel or with agate core...

**Comment by jpmckinney** [comment]
I'm getting this error: "Duplicate column names are not allowed."

There are two "tolerance" columns in the Excel file.

**Comment by onyxfish** [comment]
Yeah, I manually renamed one to test the original issue.

C

**Comment by jpmckinney** [comment]
Ah, isn't that a regression? That new behavior will have to be documented.

**Comment by jpmckinney** [comment]
Anyway, seems to be fixed. I'll open a new issue for the duplicate columns question.
