### ISSUE TITLE
Bug in parsing csv file with csvstat and csvsql

### ISSUE THREAD

**Issue by armisael** [onyxfish/csvkit#228]
Depending on what utility you are using, the parse of this csv file may fail quite dramatically:

    $ cat file.csv
    id,text,it_works
    1,"this bug seems like, a bug",1
    2,"this ''bug'' seems like, a bug",1
    3,"this ""bug"" seems like, a bug",0

`csvlook` works as expected:

    $ csvlook file.csv
    |-----+--------------------------------+-----------|
    |  id | text                           | it_works  |
    |-----+--------------------------------+-----------|
    |  1  | this bug seems like, a bug     | 1         |
    |  2  | this ''bug'' seems like, a bug | 1         |
    |  3  | this "bug" seems like, a bug   | 0         |
    |-----+--------------------------------+-----------|

as well as 'csvjson`:

    $ csvjson file.csv -i 2
    [
      {
        "it_works": "1",
        "text": "this bug seems like, a bug",
        "id": "1"
      },
      {
        "it_works": "1",
        "text": "this ''bug'' seems like, a bug",
        "id": "2"
      },
      {
        "it_works": "0",
        "text": "this \"bug\" seems like, a bug",
        "id": "3"
      }
    ]

`csvstat` however fails, as you can see in the values for the `it_works` column:

    $ csvstat file.csv
      1. id
    	<type 'int'>
    	Nulls: False
    	Values: 1, 2, 3
      2. text
    	<type 'unicode'>
    	Nulls: False
    	Values: this ''bug'' seems like, a bug, this "bug"" seems like, this bug seems like, a bug
      3. it_works
    	<type 'unicode'>
    	Nulls: False
    	Values: 1, a bug"

`csvsql` fails as well:

    $ csvsql file.csv --insert --db sqlite:///file.db
    $ sqlite3 file.db "SELECT * FROM file;"
    1|this bug seems like, a bug|1
    2|this ''bug'' seems like, a bug|1
    3|this "bug"" seems like|a bug"

**Comment by jpmckinney** [comment]
Confirming still a bug on `agate` branch.

**Comment by jpmckinney** [comment]
The bug is due to CSV sniffing. If you turn of CSV sniffing, the commands work, e.g.:

    csvstat --snifflimit 0 file.csv

**Comment by jpmckinney** [comment]
Moving discussion of sniffing behavior to #166.
