### ISSUE TITLE
in2csv should limit sniffing length by default

### ISSUE THREAD

**Issue by marians** [onyxfish/csvkit#230]
I am using in2csv to convert [this](https://github.com/marians/datahub-cgn/raw/master/data/structure/bevoelkerung/_source/bevoelkerung.csv) 6 MB CSV file to a proper CSV file.

When issuing the script this way

    in2csv -f csv -d ";" bevoelkerung.csv

it takes about 60 seconds to complete. When limiting the sniffing size like this

    in2csv -f csv -d ";" -y 100000 bevoelkerung.csv

it only takes 3 seconds.

The problem is, I didn't know about sniffing and -y until I profiled the script.

In order to improve the utility of this tool, I'd like to suggest setting a reasonable default sniffing limit. 100 KBytes seems like a reasonable amount to me, but even 1 MB would work fine on most machines, I guess.

BTW, thanks for csvkit! It's awesome!

**Comment by jpmckinney** [comment]
CSV sniffing causes a number of unusual bugs (and performance issues like this). Centralizing discussion in #166.
