### ISSUE TITLE
Feature request: provide csvstat with an option to disable or tune data type guessing

### ISSUE THREAD

**Issue by vincentborghi** [onyxfish/csvkit#231]
I have data with reference numbers which looks like "T00370201", and csvstat guesses (falsely) this is a date.

    $ (echo "ref"; echo "T00370201") | csvstat 
      1. ref
            <type 'datetime.date'>
            Nulls: False
            Values: 2037-02-01
    
    Row count: 1

I would like to have an option to disable such (in my case) misleading guesses...

**Comment by jpmckinney** [comment]
Merging into #151.
