### ISSUE TITLE
csvsql: automatic setting of boolean datatype by cell content doesnt always make sense...switch option? 

### ISSUE THREAD

**Issue by rajanski** [onyxfish/csvkit#233]
if a text column in a csv contains only 'N' and/or  'Y' it is automatically taken as a bool datatype in the resulting sql code. This is good sometimes, but sometimes one doesn't want this. Can we introduce a switch for that? 
I know there is the --no-inference option, but maybe an extra option for booleans could be nice..

Anyway the CSVKIT is a great piece of software! thanks!

**Comment by jpmckinney** [comment]
Merging into #151.
