### ISSUE TITLE
CSVSQL with "--insert" option imports faulty data to Postgres db compared with importing csvclean'ed CSV via "copy table from file.csv"

### ISSUE THREAD

**Issue by rajanski** [onyxfish/csvkit#252]
Abovesaid.

In detail, after cleaning it with csvclean (no errors reported) I imported a file with about 400k lines using the  CSVSQL "--insert" option and it turned out that the data in some some fields (not all) in the resulting database table where shifted to the preceding row.

Importing the same Csv using  "copy table from file.csv" resulted in a database table without the described errors.

I am on Ubuntu server 12.04.3 64bit , did everything locally (so no network issues possible) , with PostgreSQL 9.1

**Comment by jpmckinney** [comment]
@evz What if you pass the option `--snifflimit 0`? Seems like another sniffing bug #166

**Comment by jpmckinney** [comment]
I can't replicate:

    csvsql --db 'sqlite:///dummy.db --insert iucr_codes.csv
    sqlite3 dummy.db
    > select * from iucr_codes

All looks good. Please test on HEAD and send the commands and input that cause any remaining errors.

**Comment by evz** [comment]
Still getting the issue with that file. If you run the commands:

```
csvsql --db 'sqlite:///dummy.db' --insert iucr_codes.csv
sqlite3 dummy.db
> select * from iucr_codes where iucr = 'including public drunkenness'
```

You'll see that the `iucr` column (which should be a four character code) is being populated by things that should be in the `friendly_description` field. It seems to be getting broken on the second `"` that is within that field (part of the quotes surrounding the phrase "scandalizes the community,").

**Comment by jpmckinney** [comment]
Ah, I see. This is fixed if you run with `--snifflimit 0`. Please contribute to #166 if you don't want to have to use that option.
