### ISSUE TITLE
csvgrep doesn't support --no-header-row option

### ISSUE THREAD

**Issue by inactivist** [onyxfish/csvkit#254]
csvgrep available from pypi (csvkit 0.6.1) assumes first row is a header.  `--no-header-row` and `-H` are not recognized as valid options.  

```
$ csvgrep --no-header-row -c 9 -m "US" cities1000.txt 

usage: csvgrep [-h] [-d DELIMITER] [-t] [-q QUOTECHAR] [-u {0,1,2,3}] [-b]
               [-p ESCAPECHAR] [-z MAXFIELDSIZE] [-e ENCODING] [-S] [-v] [-l]
               [--zero] [-n] [-c COLUMNS] [-m PATTERN] [-r REGEX]
               [-f MATCHFILE] [-i]
               [FILE]
csvgrep: error: unrecognized arguments: --no-header-row
```
Not sure if this is a known issue. Edit:  I see by the changelog, 0.6.1 claims to have added the option to all tools.

```
0.6.1
-----
[snip]
* Add --no-header-row to all tools. (#189)
```

**Comment by jpmckinney** [comment]
Re-opened as #435 just makes the error from #279 go away. It doesn't allow grepping the first line of a headerless CSV.

**Comment by frederickjh** [comment]
This issue got me today. I had a file I was processing with **csvgrep**. I could not figure out why it was adding the first record to every query. I figured out that it was treating that first record as the header row. Since **csvgrep** does not support the **-H** option I had to add a header row to get around this.

**Comment by jpmckinney** [comment]
What version are you using? This should work in 1.0.2

**Comment by frederickjh** [comment]
```
$ pip show csvkit
---
Name: csvkit
Version: 1.0.2
Location: /usr/local/lib/python2.7/dist-packages
Requires: agate, agate-excel, agate-dbf, agate-sql, six
```
Not sure why it should work since **csvgrep** does not have the **-H** option. There is no what to tell it to ignore the first line in the file. If you do not have a header row in the CSV file then the first record is used as the header row and therefore rendered in every query.

**Comment by jpmckinney** [comment]
When I run `csvgrep -h` I see:

```
...
  -S, --skipinitialspace
                        Ignore whitespace immediately following the delimiter.
  -H, --no-header-row   Specify that the input CSV file has no header row.
                        Will create default headers (a,b,c,...).
  -K SKIP_LINES, --skip-lines SKIP_LINES
                        Specify the number of initial lines to skip (e.g.
                        comments, copyright notices, empty rows).
...
```

**Comment by frederickjh** [comment]
@jpmckinney True enough. I get the same help text here. However this issue is not about the help text. It is about the  fact the although the help says these options are available for csvkit commands they do not work. The header row is not rendered but a default header row is rendered. An example:

`$ csvgrep -c 2 -m "#2]" comments-test.csv`
```bash
comment," ""info"""
"From Drupal.org [issue 1335724](https://www.drupal.org/node/1335724)

>OK I got it :P The problem isn't in php files! The problem simply resides in a views (workbench_edited) automatically created when the module is installed. That view contains texts not associated to a specific text format.

 >How to: . . . (text truncated)
```

Now with the no header option -H

`$ csvgrep -H -c 2 -m "#2]" comments-test.csv`

```bash
a,b
"From Drupal.org [issue 1335724](https://www.drupal.org/node/1335724)

>OK I got it :P The problem isn't in php files! The problem simply resides in a views (workbench_edited) automatically created when the module is installed. That view contains texts not associated to a specific text format.

 >How to: . . . (text truncated)
```

So, even though the **header row** is not rendered the default **a,b** is. For my needs I needed no header row which was removed by sed.

**Comment by jpmckinney** [comment]
Aha, that behavior is not supported. Note that the documentation for -H says "Will create default headers (a,b,c,...).".

```
  -H, --no-header-row   Specify that the input CSV file has no header row.
                        Will create default headers (a,b,c,...).
```

You can just pipe to `tail -n +2` to remove the first row (assuming no newlines in the first row).

**Comment by jpmckinney** [comment]
Basically, "--no-header-row" means "The data contains no header row." It doesn't mean "Please output the data without a header row."

**Comment by frederickjh** [comment]
Yes, that I what I figured out. I think in the end I actually did use `tail` instead of `sed` as it was more performant.
