### ISSUE TITLE
Add ability to modify or friendly format numerical values

### ISSUE THREAD

**Issue by victorhooi** [onyxfish/csvkit#286]
It would be useful to have an option that friendly formatted or applied modifiers to numbers.

For example, if you had the float:

```
5081998.9369165478
```

It would print it out as:

```
5,081,998.9369165478
```

I'm currently printing out a large table of numbers using `csvlook`, and it would be much more readable if I could add commas to all the numbers, so I can get a rough idea of scale (particularly since the numbers are all left-aligned, and not right-aligned, and I can't seem to find a way in `csvkit` to change that).

Or you might have modifiers to truncate the fractional part, rounded up/down etc. which you can apply before printing.

**Comment by jpmckinney** [comment]
The implementation of this functionality is moving out of the csvkit repository into its new dependency [agate](https://github.com/onyxfish/agate/) (#515). [This is the file](https://github.com/onyxfish/agate/blob/master/agate/preview.py) that would need to be modified. You may re-open your issue on agate.
