### ISSUE TITLE
in2csv error

### ISSUE THREAD

**Issue by Raajs** [onyxfish/csvkit#318]
Invoking in2csv results in an error:  'file' object has no attribute 'rfind'

On Mac OS X 10.9.4.  Ran an update to make sure I had all the correct pieces:

sh-3.2# pip install csvkit --upgrade
Requirement already up-to-date: csvkit in /Library/Python/2.7/site-packages
Requirement already up-to-date: xlrd>=0.7.1 in /Library/Python/2.7/site-packages (from csvkit)
Requirement already up-to-date: sqlalchemy>=0.6.6 in /Library/Python/2.7/site-packages (from csvkit)
Requirement already up-to-date: openpyxl>=2.0.3 in /Library/Python/2.7/site-packages (from csvkit)
Requirement already up-to-date: six>=1.6.1 in /Library/Python/2.7/site-packages (from csvkit)
Requirement already up-to-date: python-dateutil==1.5 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from csvkit)
Requirement already up-to-date: dbf==0.94.003 in /Library/Python/2.7/site-packages (from csvkit)
Requirement already up-to-date: jdcal in /Library/Python/2.7/site-packages (from openpyxl>=2.0.3->csvkit)
Cleaning up...

Thanks!

**Comment by esafak** [comment]
I've encountered this bug too. The problem is that `in2csv` is fussy about the version of `dbf`; it _has_ to be 0.94.003; newer or older won't do, so I had to install it with `pip install --user dbf==0.94.003`. Then  `in2csv` worked once I upgraded `openpyxl`  with `pip install --user --upgrade openpyxl`.

**Comment by KarrieK** [comment]
Hey All! I have been having the same trouble with the in2csv command in csvkit. I followed your advice and installed dbf==0.94.003 (the requirement was already satisfied) and the upgraded openpyxl. 

I'm now getting File-object must be opened in binary mode thrown back at me. Any advice please?

**Comment by jamesbroadhead** [comment]
@KarrieK you are encountering https://bitbucket.org/openpyxl/openpyxl/issue/433 -- install a version of openpyxl from the 2.2 branch or newer.

**Comment by KarrieK** [comment]
All the favs. Thanks it's working a treat now.

**Comment by onyxfish** [comment]
@Kar
