### ISSUE TITLE
Feature Request: csvlook to have the ability to repeat header line

### ISSUE THREAD

**Issue by ralphschindler** [onyxfish/csvkit#330]
csvlook with the ability to repeat the header line every x lines.

**Comment by jpmckinney** [comment]
The implementation of this functionality is moving out of the csvkit repository into its new dependency [agate](https://github.com/onyxfish/agate/) (#515). [This is the file](https://github.com/onyxfish/agate/blob/master/agate/preview.py) that would need to be modified. You may re-open your issue on agate.
