### ISSUE TITLE
Cannot load international data into MySQL; delimiter confusion

### ISSUE THREAD

**Issue by shamelesshacker** [onyxfish/csvkit#344]
Great piece of software!

On the off-chance that the issue is with me and not CSVKit, I have opened a question on StackOverflow also:  http://stackoverflow.com/questions/26205666/how-to-load-international-data-into-mysql-using-csvkit

Has anyone seen the following issue?

I am loading a a pipe-delimited file of hotels into MySQL using CSVKit (https://csvkit.readthedocs.org/en/0.9.0/index.html).

Some of the hotel name fields contain "non-English" characters ( e.g. "Ånedin Hostel").  I have noticed that the character "Å" in particular tends to confuse "csvsql" regarding the pipe delimiter ("|"), causing both the record that contains the "non-English" character--and also the "next" record in the delimited file--to fail to load the fields correctly (both NULLs loaded and "fields offset" occur; the "Å" character is ommitted entirely).

The original failed configuration was discovered using the following:

MySQL Schema Character Set:  "DEFAULT COLLATE utf8_general_ci"
csvsql Command: `csvsql --blanks -d "|" -e "iso-8859-1" --db mysql://root:pwd@localhost:3306/schema_name --table table_name --insert CSVFileName.csv `

Okay, I now know that ""iso-8859-1"" is the same thing as "latin1_swedish_ci" in MySQL and that  _might_ explain the original failure...however, I cannot find the encoding parameter to pass to "csvsql" that will cause it to load "UTF-8".  I have tried every variant of "utf-8" that would seem appropriate, thus:

csvsql Command: `csvsql --blanks -d "|" -e "UTF-8" --db mysql://root:pwd@localhost:3306/schema_name --table table_name --insert CSVFileName.csv `

--or--

csvsql Command: `csvsql --blanks -d "|" -e "utf-8" --db mysql://root:pwd@localhost:3306/schema_name --table table_name --insert CSVFileName.csv `

--or--

csvsql Command: `csvsql --blanks -d "|" -e "utf8" --db mysql://root:pwd@localhost:3306/schema_name --table table_name --insert CSVFileName.csv `

I have alos tried different MySQL Schema character sets, particularly:

*  "DEFAULT COLLATE utf8_general_ci"
*  "DEFAULT COLLATE utf8_unicode_ci"
*  "DEFAULT CHARACTER SET utf8mb4"
*  "DEFAULT COLLATE utf8mb4_unicode_ci"  (see "https://mathiasbynens.be/notes/mysql-utf8mb4")

Attempting the last two configs generates an interesting error:  "OperationalError) (1118, 'Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. You have to change some columns to TEXT or BLOBs')", from:

MySQL Schema Character Set:  "DEFAULT COLLATE utf8mb4_unicode_ci"
csvsql Command: `csvsql --blanks -d "|" -e "utf8" --db mysql://root:pwd@localhost:3306/schema_name --table table_name --insert CSVFileName.csv `

I suspec that the issue lies with the encoding parameter in "csvsql", but I could be wrong.  It might be combination of the encoding and the schema character set...

The question is:  What is that parameter? or what is the combination of the parameter with the character set for international data?

CSVKit uses SQLAclchemy (http://www.sqlalchemy.org/).  According to the SQLAlchemy docs you would expect the parameter to be "utf8" (http://docs.sqlalchemy.org/en/latest/dialects/mysql.html), but as mentioned, that does not seem to work (see above).

One other bit of sleuthing:  According to the CSVKit docs "Python 3’s csv module supports unicode internally".  My Ubuntu machine's default Python version is "Python 2.7.6".  I do, however, have the latest Python 3.x installed and up-to-date, so one would think that CSVKit would use that (if available), right?  If not, how would I I make CSVKit use Python 3?

Any ideas or suggested best-practices for loading international data would be appreciated.  (I am asking for guidance on the best set of default schema settings to use with MySqL for a varied set of international data.  In effect, what is the most "future proof" way to build all MySQL schemas?)

Thanks.

Shameless

**Comment by jpmckinney** [comment]
I suspect this is fixed along with all the other encoding relate issues.

If you can send a CSV (preferably a minimal one) and the command that produces the error, I can re-open.
