### ISSUE TITLE
Can't refer to more columns after referring to a column that has a colon in it

### ISSUE THREAD

**Issue by fgregg** [onyxfish/csvkit#369]
```bash
> csvcut -c '1,B11001002 - Family households:,10' household_type.csv 
Invalid range %s. Ranges must be two integers separated by a - or : character.
```
I have tried various ways of escaping the colon, but none seem to work.

**Comment by jpmckinney** [comment]
I can only reproduce this error if that column doesn't exist:

    echo "1,2,3,4,5,6,7,8,9,10" | csvcut -v -c '1,B11001002 - Family households:,10'

If it exists, it works:

    echo "1,B11001002 - Family households:,3,4,5,6,7,8,9,10" | csvcut -v -c '1,B11001002 - Family households:,10'

It's possible your column name isn't exactly what you put. See #364 about improving that error message.
