### ISSUE TITLE
Adding Group Fields, etcs while importing csv

### ISSUE THREAD

**Issue by kiranpalla** [onyxfish/csvkit#376]
I am handling some reports which are rearranged especially keeping in view the printing needs. They've grouped some fields to restrict the data width, so that printouts can be taken easily. For example:

Sales Report - April 2014
Sl. Name            Sales
Type: Fruits
1.  Apples          100
2. Grapes          120
Type: Flowers
3.  Roses            50
4. Jasmine           70

Here Type field is grouped, to reduce the row width. While importing, this group name should also be imported. Otherwise the imported file will be of limited use. For example, the above file should import as

"Sales Report April 2014"
"Sl.","Name","Sales,"Type"
"1","Apples,"100","Fruits"
"2","Grapes,"120","Fruits"
"3","Roses","50","Flowers"
"4","Jasmin","70","Flowers"

Similar fields could exist in other places like report header / footer, page header / footer, group header / footer, subgroup header / footer. Like in the above example "April 2014" is a field data. If that is also imported properly, an additional column will look like this

"Sl", "Name","Sales","Type","Month"
"1","Apples,"100","Fruits","Apr 2014"
"2","Grapes,"120","Fruits","Apr 2014"
"3","Roses","50","Flowers","Apr 2014"
"4","Jasmin","70","Flowers","Apr 2014"

With this proper analysis can be done. In order to achive this the schema file should have more options to identify them, preferably using regular expressions

The "in2csv" should have a schema to do all this. I am not much of a programmer. But I liked csvkit and sharing my opinion, to improve the application.

**Comment by onyxfish** [comment]
Hi @kiranpalla, thanks for the ticket, unfortunately you're input format does not appear to be any kind of standard format (xls, json, etc). I don't intend to modify csvkit to support arbitrary text inputs.
