### ISSUE TITLE
Make sqlalchemy an optional dependency

### ISSUE THREAD

**Issue by alexpdp7** [onyxfish/csvkit#377]
We are using csvkit to work with CSV files and we believe we are not using any sqlalchemy-related functionality. If this library can provide significant functionality without it, could it be made an extra optional requirement?

**Comment by onyxfish** [comment]
Is there a particular reason that installing sqlalchemy is a problem? I'm generally averse to having extra requirements that have to be installed.

**Comment by alexpdp7** [comment]
Well, it's little not-so-important things:

* We're developing a remote access tool and our users are surprised when sqlalchemy is installed
* If we were to package something using csvkit we would like to avoid having to package SQL Alchemy
* Someone might already be using an older version of SQL Alchemy than what you require and might have problems using csvkit as a dependency

In any case, consider this more of a suggestion/for your consideration rather than a request :)

**Comment by jpmckinney** [comment]
I'll close for now, but if it becomes a bigger issue, I can re-open!
