### ISSUE TITLE
in2csv: Streaming option for --no-inference?  Running out of memory

### ISSUE THREAD

**Issue by nealmcb** [onyxfish/csvkit#381]
Like issue #338, I'm trying to work with data that won't fit in memory (even my 16 GB).

I'm running `in2csv --no-inference` to convert file types, change delimiters etc.
Since I don't want data inference for this particular problem, it should be possible to stream the data.

If it would be too much to implement a streaming option here, I wonder if any can recommend another good tool out there for just properly changing delimiters and the like for big data files.

**Comment by onyxfish** [comment]
Hi Neal, can you tell me which file type you were working with here? Whether or not a streaming interface could be implemented is dependent on which file conversion you're doing. Several of them are deferred to dependencies that buffer the file. A streaming interface would probably be pretty simple for CSV-to-CSV and would be a welcome addition.

**Comment by nealmcb** [comment]
I'm definitely interested in csv-to-csv, and that was my initial use case.
Thanks!
