### ISSUE TITLE
csvclean must must respect delimiter in output file

### ISSUE THREAD

**Issue by AntoineDcode** [onyxfish/csvkit#384]
Hi,

The output file of "csvclean" use ',' (comma)  as delimiter even if the delimiter option (-d) has been specified. 

Maybe it's better that the output have the same delimiter than the input.

Regards

**Comment by onyxfish** [comment]
Please see the "Principles" section of the docs. csvkit outputs in a "standard" format by design.

http://csvkit.readthedocs.org/en/0.9.1/contributing.html#principles

If you need to convert to a custom format use `csvformat`:

http://csvkit.readthedocs.org/en/0.9.1/scripts/csvformat.html
