### ISSUE TITLE
csvcut output contains multiple header rows

### ISSUE THREAD

**Issue by diehl** [onyxfish/csvkit#390]
I'm using csvcut to filter a CSV file with about 1.5 million rows down to a subset of the columns. I've just discovered that the resulting output CSV has two rows containing the column labels: one at the top of the file as expected and another about 750k rows in. It's the latter that I'm completely baffled by. 

I'm simply doing a call to csvcut of the form:
csvcut -c <column name 1> <column name 2> ... <column name N> input.csv > output.csv

Potential bug?

**Comment by JoeGermuska** [comment]
Are you certain that this is only in the`csvcut` output and not in the original file?

**Comment by diehl** [comment]
In fact that was indeed the case. Found a problem further upstream in the processing.
