### ISSUE TITLE
Unable to process tutorial file

### ISSUE THREAD

**Issue by smach** [onyxfish/csvkit#391]
After downloading the tutorial data file, when I try running 

    in2csv ne_1033_data.xlsx > data.csv

I get the error message

    'NoneType' object is not iterable

This seems to be an issue with this specific tutorial file, because I was able to import my own small test spreadsheet OK. Someone may want to take a look at that tutorial test-data spreadsheet. FYI I tried importing it into R a couple of different ways, one way worked fine but another way choked saying 'invalid sheet xml'. 

I'm running csvkit on OS X Yosemite with the standard Python installed by default (2.7.6).

**Comment by JoeGermuska** [comment]
The conclusion on the NICAR-L list was that this is a problem with `csvkit`'s openpyxl dependency. A fresh install today installed `openpyxl` 2.2.0. Downgrading with `pip install openpyxl\<2.2` worked.

**Comment by JoeGermuska** [comment]
Looks like this is a [known bug in Openpyxl](https://bitbucket.org/openpyxl/openpyxl/issue/433/load_workbook-excelpy-does-not-accept) 

A workaround would be to set the dependency to `openpyxl==2.2.0-b1` (as suggested in the linked bitbucket issue) although perhaps this will be fixed before a new csvkit release would get cut anyway.
