### ISSUE TITLE
HTML entities parsing error

### ISSUE THREAD

**Issue by CMCDragonkai** [onyxfish/csvkit#392]
In one of my columns I have this as the data:

```
O&#039;Connor
```

However when csvcut and csvgrep tries to parse it, it assumes that the `;` represents a separation into 2 columns. This is incorrect as the entire htmlentity needs to be considered as a single piece of data.

Is there any way to fix?

Libreoffice calc is currently parsing it correctly.

**Comment by onyxfish** [comment]
Hi Roger, you should be able to specify the delimiter explicitly with the `-d` option. That will override csvkit's built-in delimiter detection and should allow this data to be parsed correctly.

**Comment by CMCDragonkai** [comment]
Oh so you're saying that just using automatic detection, it will consider all possible delimiters? I realised by CSV is delimited by commas. If the majority of the CSV is delimited by commas, can't the csvcut figure out that therefore `;` is not a delimiter?

Or if it can't do this, at least give me feedback that the CSV has different possible delimiters, so if I'm doing any kind quick csv manipulation I don't make mistakes. I only caught it, because I wanted to verify if csvcut was doing the right thing.

**Comment by onyxfish** [comment]
Not really. 1) The delimiter detection is baked into the Python csv library and it doesn't provide a window into the selection logic that it uses. 2) Theoretically it's picking the most common possible delimiter from the sample it uses to determine the format of the file, which means there must be a fair number of semicolons. You could try increasing the sample size with ``--snifflimit`` option to see if it picks up the correct delimiter, but setting the `-d` option is probably cleaner.

Believe it or not, I've seen a whole lot of CSV's delimited with `;`. It's one of about 10 possible delimiters csvkit will detect.

**Comment by CMCDragonkai** [comment]
The csv I was using definitely did not have any semicolons except 2 places.

**Comment by jpmckinney** [comment]
@CMCDragonkai The CSV dialect sniffer doesn't check the entire file (that would be very slow, and would mean that we can't do streaming on any file). To disable sniffing, use `--snifflimit 0` and set the delimiter manually. If you prefer a different behavior, please contribute to #166
