### ISSUE TITLE
local variable 'j' referenced before assignment

### ISSUE THREAD

**Issue by dougneedham** [onyxfish/csvkit#393]
In table.py on line 237, I had to add j = 0 to define the variable J in order to get csvkit to work in my environment. 
Is this a bug, or did I do something else wrong? 
The subject line was the error I receieved for all of the utilities like csvstat, and csvsql. 
My change: 
        for i, row in enumerate(rows):
-->       j = 0
            for j, d in enumerate(row):

Thank you, 

Doug

**Comment by onyxfish** [comment]
Hi Doug, it shouldn't be necessary to explicitly define that variable. Can you tell me more about what OS and what version of Python you're running?

**Comment by dougneedham** [comment]
Happens in multiple environments.
Windows 7 - Python 2.7
RHEL 6.5 - Python 2.6 (AWS)
When I run the command csvstat somefile.csv
I get: 
local variable 'j' referenced before assignment
The command can be csvstat, or csvsql. I did not test all of the commands but these are the two that I need for my process. 

Please let me know if you need any further information. 

Thank you

**Comment by dwalton64** [comment]
I am seeing the same problem on Python 2.7.6 in Linux Mint 17.1

This prevents me from using the released version of cvskit.

    Traceback (most recent call last):
      File "/usr/local/bin/csvstat", line 9, in <module>
        load_entry_point('csvkit==0.9.1', 'console_scripts', 'csvstat')()
      File "/usr/local/lib/python2.7/dist-packages/csvkit/utilities/csvstat.py", line 246, in launch_new_instance
        utility.main()
      File "/usr/local/lib/python2.7/dist-packages/csvkit/utilities/csvstat.py", line 76, in main
        **self.reader_kwargs
      File "/usr/local/lib/python2.7/dist-packages/csvkit/table.py", line 244, in from_csv
        j += 1

**Comment by shane-axiom** [comment]
Same when running csvsql from csvkit 0.9.1 under Python 2.7.9 in Debian Jessie 8.1.

    local variable 'j' referenced before assignment

**Comment by hydrosIII** [comment]
Hi confirming this bug appears in arch linux using python 2.7.0

**Comment by katylava** [comment]
I experience this with Python 2.7.11 (brew installed on my Mac). It only happens for some files, not others, depending on the line endings. Seems to happen for files created by programs which create an *extra* line ending.

```
> file xa*
xaa: ASCII text, with CRLF line terminators
xab: ASCII text, with CRLF, CR line terminators
> csvstat xab
local variable 'j' referenced before assignment
> csvstat xaa
# normal csvstat output
```


Example file: [sample.csv.txt](https://github.com/onyxfish/csvkit/files/74387/sample.csv.txt)

**Comment by jpmckinney** [comment]
`j` is undefined if `row` is an empty list. Fixed in #489.

**Comment by pal** [comment]
I get this error in the latest pip (0.9.1), is this fix released yet? @jpmckinney

**Comment by jpmckinney** [comment]
No, but you can instead from GitHub:

    pip install -e git+git://github.com/onyxfish/csvkit.git@master#egg=csvkit

**Comment by shane-axiom** [comment]
Would be nice to get a bugfix release (0.9.2) with this included...

**Comment by superurbi** [comment]
The same problem here!!!! 
any estimated time for 0.9.2 release for Windows? the upgrade using this:
pip install -e git+git://github.com/onyxfish/csvkit.git@master#egg=csvkit
doesn't work for me as a lot of package issues arise!
Regards,

**Comment by jpmckinney** [comment]
@superurbi The error only occurs if your CSV is empty, or if you used other csvkit tools to cut your CSV down to 0 columns.
