### ISSUE TITLE
Unfix openpyxl version once encoding bug is fixed

### ISSUE THREAD

**Issue by onyxfish** [onyxfish/csvkit#394]
See #391 and https://bitbucket.org/openpyxl/openpyxl/issue/433/load_workbook-excelpy-does-not-accept

**Comment by barraponto** [comment]
It seems to have been fixed since openpyxl 2.2.1.

**Comment by jpmckinney** [comment]
Unfixed in https://github.com/onyxfish/agate-excel/blob/master/setup.py

**Comment by onyxfish** [comment]
This will actually go away entirely since the dependency moves to `agate-excel`.
