### ISSUE TITLE
Display table names for input files by "csvsql"

### ISSUE THREAD

**Issue by elfring** [onyxfish/csvkit#395]
I suggest to add the capability to [the tool "csvsql"](http://csvkit.readthedocs.org/en/0.9.1/scripts/csvsql.html "SQL statement execution on CSV files") that names can be displayed for the tables which are generated for the passed files.

**Comment by jpmckinney** [comment]
I'm not sure I understand. When you run `csvsql examples/dummy.csv` the table name is in the output. What are you requesting?

**Comment by elfring** [comment]
Can the tool "csvsql" convert names from input files into SQL table identifiers?
Which interface will be appropriate to retrieve results from such a name selection?

**Comment by jpmckinney** [comment]
Can you give me some an example of the input, command, and output that would fit what you're describing?

**Comment by elfring** [comment]
My feature request affects evolving functionality.

* Do you expect that input file names should be kept unchanged for the evaluation of a SQL script?
* Does the passed SQL script need to take care of special names from the provided input manually?

**Comment by jpmckinney** [comment]
What's the difference between this and #521?

**Comment by elfring** [comment]
It was just an earlier idea. - It can be adjusted after [your feedback for the issue "Support for direct queries on files with special characters in their names"](https://github.com/onyxfish/csvkit/issues/521#issuecomment-174225366 "Queries on files with special characters in their names").

**Comment by jpmckinney** [comment]
Ok, merging with #521.
