### ISSUE TITLE
CSVjson includes key as a value

### ISSUE THREAD

**Issue by stevage** [onyxfish/csvkit#400]
```
csvjson -k key <<EOF
key,something,other
hello,blah,fish
goodbye,moreblah,morefish
EOF

{"hello": {"other": "fish", "something": "blah", "key": "hello"}, "goodbye": {"other": "morefish", "something": "moreblah", "key": "goodbye"}}
```

Seems to me the output should be:

```
{"hello": {"other": "fish", "something": "blah"}, "goodbye": {"other": "morefish", "something": "moreblah"}}
```

It's weird to have the key included as a value.

**Comment by jpmckinney** [comment]
@onyxfish How do you feel about changing the output on this?

**Comment by onyxfish** [comment]
I don't feel strongly about it one way or another, but it is sometimes useful to have the key column in the original data. Is there a compelling argument for removing it?

**Comment by jpmckinney** [comment]
I think it's just aesthetics.

**Comment by jpmckinney** [comment]
Since there's no compelling argument and it causes no issues for anyone, closing.
