### ISSUE TITLE
csvsql with --insert flag should insert on empty table with matching schema

### ISSUE THREAD

**Issue by samzhang111** [onyxfish/csvkit#402]
Sometimes I create a table with csvsql, and the insert fails for whatever reason. The expected behavior upon re-run is for the data to insert if the schema matches, otherwise fails. Instead, it throws a sqlalchemy stack trace that ends with:

`sqlalchemy.exc.OperationalError: (OperationalError) (1050, "Table '<table>' already exists")`

Then I have to execute separate commands to drop the empty table, before re-inserting.

**Comment by jpmckinney** [comment]
You can pass `--no-create` instead of dropping the table.
