### ISSUE TITLE
csvlook: arrange and include the delimiter, but skip the frames

### ISSUE THREAD

**Issue by chrisbra** [onyxfish/csvkit#403]
Hi,
I am the author of a csv plugin for [Vim](https://github.com/chrisbra/csv.vim/) [Screencast](http://www.256bit.org/~chrisbra/csv.gif) (Look for the :ArrangeCol command) and I am considering to use csvlook to render nice column view of the csv file. Currently I am doing this manually using some regexp magic and while this works okay, it can cause problems for huge csv, that cause Vim to allocate so much memory that it will get killed. So I thought about alternatives.
In order to make use of csvlook, I'd suggest a new optional argument, that skips generating the ascii frames around the table and just columnizes the output, but keeps the delimiter so the user can simply edit a nice excel view of the csv file.

Would that be possible?

(Note: My plugin also allows to arrange each column individually, but for now, it would be okay for me, if this is not yet implemented.)

**Comment by jpmckinney** [comment]
This functionality is moving out of csvkit into [agate](https://github.com/onyxfish/agate/) (#515). The file that would need to be modified is https://github.com/onyxfish/agate/blob/master/agate/preview.py You may re-open your issue there.
