### ISSUE TITLE
csvjoin: Add --no-header-row support

### ISSUE THREAD

**Issue by nagabhushan** [onyxfish/csvkit#404]
Hi ,

Thanks for the csvkit,

I tried with csv without headers and results were wrong.
After adding header it worked.Tried with -H or --no.header option it gives error.

Please let me know how to use it.

**Comment by jpmckinney** [comment]
Renaming issue.

**Comment by onyxfish** [comment]
How would you join without headers? By column index?

**Comment by jpmckinney** [comment]
That was my thinking.

**Comment by jpmckinney** [comment]
Implemented in #570. Can't use agate yet, as it seems agate uses column names, not indices. (Also, agate requires headers.)
