### ISSUE TITLE
csvsql does not work from within a script that is run as a cron job

### ISSUE THREAD

**Issue by 1Map** [onyxfish/csvkit#415]
I have tried with the following:

1) Created a php script that execute csvsql
2) Created a python script that execute csvsql

Both these scripts run "forever - while True"
Within the while loop it tests for a certain criteria, and if met it will execute csvsql
Both these scripts works 100% when run from the command line, for example:

sudo php myscript.php
sudo python myscript.py

The problem is, the moment I create a service (cron) from these scripts, then csvsql fails (Does not create my postgresql table and does not give an error message)

Always I execute the scripts with sudo rights.

Example:

/usr/local/bin/csvsql --db postgresql://pguser:pgpass@192.168.50.77/mypgdb --no-constraints --insert --table geocoding_854EF913-3C06-4E6D-A56F-A89425AACCFB_1 "/tmp/854EF913-3C06-4E6D-A56F-A89425AACCFB/1/Test.csv"

**Comment by vladdancer** [comment]
Hi. Have you looked an issue #342 ?

**Comment by jpmckinney** [comment]
Seems to be duplicate.
