### ISSUE TITLE
csvlook -d for tab delimited files

### ISSUE THREAD

**Issue by crazyhottommy** [onyxfish/csvkit#417]
Hi there,
I know for tab delimited files I can use csvlook -t
how can I use the -d flag for the same task? 
`csvlook -d \t` did not work

Thank you,
Ming Tang

**Comment by crazyhottommy** [comment]
I found that:
`csvlook -d $'\t'` will do the trick.

Ming

**Comment by jpmckinney** [comment]
Thanks for posting the solution!

**Comment by gsime1** [comment]
This also works when you're using `csvsql`:  `csvsql -d $'\t'
