### ISSUE TITLE
csv tools doesn't work in a cron job

### ISSUE THREAD

**Issue by vladdancer** [onyxfish/csvkit#420]
Hi, thanks for very handy tool. I must say that **in2csv**, **csvformat** tools doesn't save data to the file if it used as cron job.

`*/5 * * * * cd /root/app && in2csv -f json source.json  > dest.csv`
Doesn't work

or

`*/5 * * * * cd /root/app && in2csv -f json source.json  | csvformat -D ";" dest.csv`
Doesn't work

`*/5 * * * * cd /root/app && cat source.json > dest.csv`
Works

At the same time running in2csv in a shell works great, `cd /root/app && in2csv -f json source.json  > dest.csv`

Could you please correct me?

**Comment by vladdancer** [comment]
I assume this relates to the #415, #342

**Comment by vladdancer** [comment]
Ok, playing with stderr give me an info that command in2csv was not found, so I've just added full path to the job (/usr/local/bin/in2csv) and it works now.

Sorry, issue was related to the cron job itself not to this tool. Thanks for the tool!

**Comment by kintaro1981** [comment]
Wow! I lost a whole afternoon on this. Thank you 2015's @vladdancer from the 2022 😄  

But are you sure that the problem is about cron?
Why in2csv doesn't work if launched from a cronjob without the full path?
Ins't it a bug?
