### ISSUE TITLE
csvsort munges output when column contains single quoted strings

### ISSUE THREAD

**Issue by slackorama** [onyxfish/csvkit#421]
With the following data:

       id,command
       2,/foo/bar 'name' 'xxxx'
       1,/another/command 'xxx'

csvsort truncates the last column and quotes everything:

    $ echo "id,command\n2,/foo/bar 'name' 'xxxx'\n1,/first/command xxx" | csvsort -c 1
    "id,command"
    "1,/first/command"
    "2,/foo/bar"

If the column only has one quoted string in it though, it produces the correct results:

      $ echo "id,command\n2,/foo/bar 'name'\n1,/first/command xxx" | csvsort -c 1
      id,command
      1,/first/command xxx
      2,/foo/bar 'name'

**Comment by slackorama** [comment]
Looks like the problem is with `csvkit.table`.

I'll see if I can fix it.

**Comment by jpmckinney** [comment]
See #166 for discussion. Reading an entire file to determine the CSV dialect is too slow; reading only a part of the file will always be error-prone. As you discovered, it's possible to construct very small examples that produce incorrect behavior. One option would be to turn off sniffing by default. However, we would then be flooded with issues about the many non-standard dialect CSVs; we have to choose between that and the trickle of issues about sniffing doing the wrong thing. Feel free to contribute to #166 if you think there's a better alternative.
