### ISSUE TITLE
csvgrep -m with non-ascii pattern gives UnicodeDecodeError

### ISSUE THREAD

**Issue by spivachek** [onyxfish/csvkit#422]
This works ok:

```bash
echo -e 'name\nsome Вася' | csvgrep -c name -m some
```

But this gives UnicodeDecodeError:

```bash
echo -e 'name\nsome Вася' | csvgrep -c name -m ася
```

Possibly pattern is converted to unicode with ascii by default? Use utf-8 maybe.

**Comment by jpmckinney** [comment]
I can't reproduce on master. Likely fixed by #486, for same reason as #477.
