### ISSUE TITLE
Error infering datetime with 00:00:00 time

### ISSUE THREAD

**Issue by jmartinter** [onyxfish/csvkit#424]
I found that when loading a csv with date/time + timezone fields (infer_types=True), if hour is 00:00:00, only the date part is considered. As a result you get something of this kind: datetime.date(2015, 6, 25) instead of datetime.date(2015, 6, 25, 0, 0, 0, tzinfo=tzlocal())

Hope this might be useful for you!

**Comment by jpmckinney** [comment]
Noting that we should write a test for this to see if behavior has changed thanks to `agate`.

**Comment by onyxfish** [comment]
It has definitely changed, though it would be good to verify it's actually *fixed*. Here are the relevant agate tests: https://github.com/onyxfish/agate/blob/master/tests/test_data_types.py#L209

**Comment by jpmckinney** [comment]
Added test. Works. Closed.
