### ISSUE TITLE
in2csv converts dates to integers, integers to dates.

### ISSUE THREAD

**Issue by carrutstick** [onyxfish/csvkit#439]
I have a .xlsx file downloaded from [this URL](http://www.cmegroup.com/trading/interest-rates/files/TCF.xlsx), which contains rows like the following: 

![s](https://cloud.githubusercontent.com/assets/436975/9475379/5b329a58-4b34-11e5-8233-d4133aeaf23e.png)

but when I attempt to convert this file using in2csv, I get output lines such as:

    3,,0.625,42185,42916,912828XJ4,1900-01-26,0.9119,-----,...
    4,,0.875,41835,42931,912828WT3,1900-01-27,0.9122,-----,...

Instead of entries recognizable as dates we get integers (the number of days since 1900-01-00), and instead of integers we get dates.

I have tried several different versions of csvkit, and the last one that converts this file properly is 0.5.0.

**Comment by ThomasLee969** [comment]
It seems a [known bug](https://bitbucket.org/openpyxl/openpyxl/issues/440/regression-220-failed-to-read-a-xslx-file) of `openpyxl` package and has been [fixed](https://bitbucket.org/openpyxl/openpyxl/commits/4b03e80bfa21). I can reproduce the bug and after I upgrade `openpyxl` to 2.2.5 everything's fine.

I would suggest to upgrade `csvkit`'s `openpyxl` dependency.

**Comment by carrutstick** [comment]
Great, thanks for the info!
