### ISSUE TITLE
csvgrep count option?

### ISSUE THREAD

**Issue by jungle-boogie** [onyxfish/csvkit#441]
Hello,

Thank you for your great tool. It shows that you made the tool to work for you and thousands of other users have found it invaluable to assist with csv data.

I don't think this exists but is there a way to grep and count the results? 
http://csvkit.readthedocs.org/en/latest/scripts/csvgrep.html

For instance, if I just wanted to count occurrences of `702` on the column AreaCode, I could do this:
`csvgrep -c -C AreaCode -r 702 5-digit%20Commercial.csv`

Does this already exist?

**Comment by edwardros** [comment]
You could use GNU coretools to achieve this:

     csvgrep -c -C AreaCode -r 702 5-digit%20Commercial.csv | tail -n +2 | wc -l

The `tail -n +2` is to remove (not count) the header row, and `wc -l` counts the number of lines of output.

**Comment by jungle-boogie** [comment]
Hi @edwardros,

Thanks for the reply. I don't know if the `-C` actually, exists, that was my shorthand way to illustrate a count option, but your `--count` option with `csvstat` may work fine.

Thanks for the tip with tail & wc.

**Comment by edwardros** [comment]
`csvstat` is a better option as wc will give incorrect results if any field contains a newline, whereas (if it's properly quoted) csvstat should give correct results.

**Comment by jpmckinney** [comment]
Thanks, @edwardros ! csvkit is about combining tools, instead of having one tool do everything.

**Comment by jungle-boogie** [comment]
>  instead of having one tool do everything.

So why are you implementing grep then?

**Comment by jpmckinney** [comment]
Grep lets you match specific columns?
