### ISSUE TITLE
Issue with python-dateutil

### ISSUE THREAD

**Issue by kimbria7** [onyxfish/csvkit#449]
I've been trying to run any basic function within csvkit and am getting the following error: 
pkg_resources.DistributionNotFound: The 'python-dateutil==2.2' distribution was not found and is required by csvkit

I did: 
pip list | grep dateutil

and the output to ^ was: "python-dateutil (2.4.2)"

I'm guessing csvkit is specifically looking for 2.2?

**Comment by JDFagan** [comment]
I have same problem

**Comment by kimbria7** [comment]
Hey JDFagan, I actually resolved the issue. If I remember correctly, I think I installed all the packages again, and it somehow worked. If I manage to exactly remember what I did, I'll let you know

**Comment by jpmckinney** [comment]
@JDFagan If re-installing as @kimbria7 suggests doesn't solve the issue, I can re-open.
