### ISSUE TITLE
csvstat 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by davbre** [onyxfish/csvkit#453]
Using this file:
 
[http://data.cso.ie/downloads/foreign-speak-english/ability_to_speak_english__spea.tsv](http://data.cso.ie/downloads/foreign-speak-english/ability_to_speak_english__spea.tsv)

I run this from the command line:

    csvstat --max -y 2048 "ability_to_speak_english__spea.csv"

It runs fine and I get these results:

    1. col1: W35014
    2. col2: ST
    3. col3: Árainn Mhór
    4. col4: well
    5. col5: 326036
    6. col6: speakers of foreign languages

However, if I run the same command from a script it fails and I get this message:

    'ascii' codec can't encode character u'\xc1' in position 11: ordinal not in range(128)

I don't know if this is an issue on my setup or a problem with csvkit/csvstat so am posting this in case it's the latter.

**Comment by edwardros** [comment]
Hi @davbre ,

could you please post a minimal script that fails? I can invoke it successfully from a script.

**Comment by tigerfoot** [comment]
Look like the script doesn't setup the LC
# LC is mandatory to have codec using utf-8.py and not ascii
LC_ALL=en_US@UTF-8 yourscript 
should fix it

**Comment by davbre** [comment]
Thanks for the tip @tigerfoot. I'm currently working on a different machine to the one I was using when I opened the issue. I've just tried to re-create the error message but the command is now working fine  from a script, so I'm going to close the issue.
