### ISSUE TITLE
Citing csvkit in academic publication.

### ISSUE THREAD

**Issue by hydrosIII** [onyxfish/csvkit#454]
Currently I'm using csvkit for some data analysis, this data should be published in an academic writing.
Gnu/parallel for example, shows a way to cite it in your work, also the most of R libraries show this also. How should I cite csvkit?  I want to give the right credit.

**Comment by jpmckinney** [comment]
Can you give an example of how those other libraries do citations?

**Comment by hydrosIII** [comment]
For parallel if you use parallel--bibtex it gives:

@article{Tange2011a,
  title = {GNU Parallel - The Command-Line Power Tool},
  author = {O. Tange},
  address = {Frederiksberg, Denmark},
  journal = {;login: The USENIX Magazine},
  month = {Feb},
  number = {1},
  volume = {36},
  url = {http://www.gnu.org/s/parallel},
  year = {2011},
  pages = {42-47}
  doi = {10.5281/zenodo.16303}
}

The R project.


@Manual{,
  title        = {R: A Language and Environment for Statistical
                  Computing},
  author       = {{R Core Team}},
  organization = {R Foundation for Statistical Computing},
  address      = {Vienna, Austria},
  year         = 2015,
  url          = {https://www.R-project.org}
}

Ggmpa the R library

  @Article{,
    author = {David Kahle and Hadley Wickham},
    title = {ggmap: Spatial Visualization with ggplot2},
    journal = {The R Journal},
    year = {2013},
    volume = {5},
    number = {1},
    pages = {144--161},
    url =
      {http://journal.r-project.org/archive/2013-1/kahle-wickham.pdf},
  }

**Comment by jpmckinney** [comment]
@onyxfish What do you think of:

```
@Manual{,
  title        = {csvkit},
  author       = {Christopher Groskopf},
  year         = 2015,
  url          = {http://csvkit.readthedocs.org/}
}
```

**Comment by onyxfish** [comment]
Can we do

```
@Manual{,
  title = {csvkit},
  author = {Christopher Groskopf and contributors},
  year = 2015,
  url = {http://csvkit.readthedocs.org/}
}
```

Otherwise that looks great.

**Comment by jpmckinney** [comment]
Sure! @hydrosIII Where do those other libraries publish their recommended citation?

**Comment by hydrosIII** [comment]
Yeah, that is great. 
R libraries publish this in the Cran repo:

https://cran.r-project.org/web/packages/ggmap/citation.html

Parallel just indicate this in the webpage, and the citation is hardcoded in the code.

http://www.gnu.org/software/parallel/

 i guess you can add this info in both github and the docs.

**Comment by jpmckinney** [comment]
@onyxfish Any suggestion for where to add this to docs? It doesn't seem to fit anywhere, so my thoughts are either index.rst or a new, last top-level menu item.

**Comment by hydrosIII** [comment]
You could also add something in the code like a option csvcut --bibtex, or something. 
Also on a brief cheerful note i just delivered a speech on a data analysis involving csvkit in a datascience meetup in Mexico. It was a great success, thank you for the software.

**Comment by onyxfish** [comment]
@jpmckinney I'm fine with either of those options. Whichever seems best to you.

@hydrosIII That's great! Glad to hear it went well!
