### ISSUE TITLE
Change output filename from <stdin>_out.csv (invalid on Windows) to stdin_out.csv

### ISSUE THREAD

**Issue by aborruso** [onyxfish/csvkit#456]
Hi,
usually I use csvkit inside cygwin, and it works great.

But I have strange stdin problem. If I run the below command on my debian machine I have no problem.

    curl -s "http://217.222.248.115/BdProcedimenti/consulta/tmp/ProcOpenData.csv" | csvclean -d ";" -u 3 -e Windows-1252

If I run it in cygwin instead I have:
[Errno 22] invalid mode ('w') or filename: '<stdin>_out.csv'

I know it's not a csvkit problem but something related on environment settings, but I do not know where to start.

Thank you

**Comment by aborruso** [comment]
It seems something related to stdin.

If I write:

    csvclean -d ";" -u 3 -e Windows-1252 MyInputFile.csv

I have `No errors`, csvclean reply properly to me.

But if I write:

    csvclean -d ";" -u 3 -e Windows-1252 < MyInputFile.csv

I have 

    [Errno 22] invalid mode ('w') or filename: '_out.csv'

**Comment by aborruso** [comment]
The problem seems related to the output file and to its name. If I set `-n` argument ( no output created) I have no problem.

If I remove `-n` and run

    curl -s "http://217.222.248.115/BdProcedimenti/consulta/tmp/ProcOpenData.csv" | csvclean -d ";" -u 3 -e Windows-1252

I have `[Errno 22] Invalid argument: '<stdin>_out.csv'`

`<stdin>_out.csv` is the standard the name of the output file. Inside windows `<` and `>' are forbidden for naming a file.

What do you think to change the default name of output file when the input is a stdin?

Thank you

**Comment by jpmckinney** [comment]
Fixed. Thanks for reporting!
