### ISSUE TITLE
Subprocess and CSVSQL

### ISSUE THREAD

**Issue by bubblebeex** [onyxfish/csvkit#463]
I tried to call csvsql through subprocess and I tried to save the results of the query in a file, but the file is blank (it works perfectly from command line).

import subprocess
results = ' c:\\path\\to\\file.csv '
my_cmd = ' csvsql --query "select * from data where foo > xyz" c:\\path\\to\\data.csv '
with open(results, 'a') as doc:
    query = subprocess.Popen(my_cmd, shell=True, stdout=doc, stderr=doc)

Subprocess csvsql doesn't work neither with print

import subprocess
my_cmd = ' csvsql --query "select * from data where foo > xyz" c:\\path\\to\\data.csv '
query = subprocess.Popen(my_cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
for line in query.stdout.readlines():
   print line

What am I doing wrong? Thank you in advance
P.S. I'm using python 2.7, win64

**Comment by bubblebeex** [comment]
Resolved. The solution is the same that  @aborruso found for cron job ( A strange cron problem with csvsql #342 ).

**Comment by jpmckinney** [comment]
Closing as reported as resolved.
