### ISSUE TITLE
Trouble with the SQL Alchemy strings

### ISSUE THREAD

**Issue by joshfraser** [onyxfish/csvkit#467]
I'm stoked to have discovered csvkit.  It makes me sad to think how many hours have been wasted doing these types of data manipulations by hand in the past.  Thanks for your work on this & releasing it as open-source.

I'm having trouble connecting to a local database using the SQL Alchemy strings.  Everytime I do something like:

> csvsql --db 'postgres://localhost:5432' --insert --tables table data.csv 

I get:

> You don't appear to have the necessary database backend installed for connection string you're trying  to use. Available backends include:

> Postgresql:	pip install psycopg2
> MySQL:		pip install MySQL-python

> For details on connection strings and other backends, please see the SQLAlchemy documentation on dialects at: 

> http://www.sqlalchemy.org/docs/dialects/

I've installed both psycopg2 and MySQL-python, but neither option works for me.  I have no problem if I open a python prompt and type "import psycopg2" but I've had no luck getting the connection to work via csvsql.

Any tips on what I should try next?  I'm running python 3.5, btw.

**Comment by jpmckinney** [comment]
Are you in a virtualenv?

I have csvkit installed system-wide, but not psycopg2. When I installed csvkit in a virtualenv alongside psycopg2, I could run `~/.virtualenvs/myvirtualenv/bin/csvsql  --db 'postgres://localhost:5432/mydatabase' --insert --tables mytable mycsv.csv` If you install both system-wide, it will also probably work.

**Comment by jpmckinney** [comment]
See #522 for discussion of same issue. Can re-open if the solution towards the end of #522 doesn't work.
