### ISSUE TITLE
csvsql recognizing different column/variable names as different data types across a set of files

### ISSUE THREAD

**Issue by rishde** [onyxfish/csvkit#470]
Hello, 

I have a set of insurance claims data, a file for each year. I am trying to convert these .csv files to sql create table statements using the following command:

csvsql -i postgresql filename

The statements were created successfully. However, csvkit inferred different data types for the same variable across these files

Is there a feature that I could use to help correct this problem?

**Comment by ethanpooley** [comment]
@rishde I am not one of the experts around here, but saw this as I was searching for `csvsql` issues related to my own current use of the tool. I don't believe there is a feature that will help you with that problem. #151 seems to be what you are after, but it hasn't been implemented yet.

Can you just use an `ALTER TABLE` statement in SQL after import to force the same type on all of these columns? As long as the data hasn't been transformed as a result of the type inference (#291) I should think this would work.

**Comment by jpmckinney** [comment]
Closing in favor of centralizing discussion in #151.
