### ISSUE TITLE
Feature: convert csvlook table to csv

### ISSUE THREAD

**Issue by kwrooijen** [onyxfish/csvkit#478]
The table that `csvlook` creates is conveniently equal to an [emacs org-mode](http://orgmode.org/) table and I use it quite often to generate my tables. It would be nice to be able to convert these tables back to csv / json files. 

I haven't been able to find this feature in the docs, however I can imagine this would be either low priority or not desired.

**Comment by jpmckinney** [comment]
Those tables aren't a standard or popular format, so I'm closing to keep csvkit focused on formats like DBF, Excel, etc.
