### ISSUE TITLE
Read and write CSVs from Google Docs

### ISSUE THREAD

**Issue by onyxfish** [onyxfish/csvkit#48]

**Comment by sbma44** [comment]
I'm taking a pass at the writing-to-sheets side of this; will hopefully have a PR soon, might need some help getting proper tests up in tox

**Comment by eyeseast** [comment]
I like the idea of making it easier to work with Google, but if we're just talking about supporting fetching CSV data from URLs, is this any different from just using `curl`?

```
curl http://example.com/somefile.csv | csvcut -c 1,2,3 | csvstat
```

**Comment by sbma44** [comment]
@eyeseast I'm focusing on putting data into Google Sheets from the command line, not retrieving it from there (though that would be doable as well)

**Comment by jpmckinney** [comment]
Re: reading CSVs from web, @eyeseast is right to suggest just using Unix piping with a utility like `curl`.

Re: writing CSVs to the web, I think that should also just be the responsibility of some utility that takes a CSV as STDIN and writes it to whatever services it supports. I don't think csvkit should know about authentication with Google Spreadsheets or whatever else. For example, `s3cmd` allows uploading to S3 from STDIN. A Google Spreadsheets command-line tool can follow the same design.
