### ISSUE TITLE
csv2sql quotes column names only if there is an upper case letter in the header name

### ISSUE THREAD

**Issue by stefanproell** [onyxfish/csvkit#480]
I am using csv2sql for creating SQL table schemata from CSV files. I noticed that in the CREATE TABLE statement provided by csv2sql after parsing, that some column names are not enclosed by double quotes while all other column names are quoted. The behaviour does neither depend on the column type, the properties of the column values nor the column name per se. It took my quite some time to figure out, that the tool only then encapsulates the column name in double quotes, if and only if the header name contains at least one upper case letter.

Example CSV file with two columns:
    columnA	columnB
    1	                4
    2	                5
    3	                6

#> csvsql -t  testfile.csv

provides expected:
CREATE TABLE testfile (
	"columnA" INTEGER NOT NULL, 
	"columnB" INTEGER NOT NULL
);

But the file 
    columna	columnb
    1	                4
    2	                5
    3	                6
gives as NOT expected, the statement:
CREATE TABLE testfile (
	columna INTEGER NOT NULL, 
	columnb INTEGER NOT NULL
);

This is an unexpected behaviour, because the quoting of the column names depends for instance on camel casing column names. Is this a bug?

**Comment by jpmckinney** [comment]
csvkit uses sqlalchemy, and sqlalchemy only quotes a column name if necessary. In PostgreSQL, for example, a column name with an uppercase letter must be quoted, otherwise it will error.

I don't see why omitting optional quotes would be a bug, so closing.
