### ISSUE TITLE
cancelling request

### ISSUE THREAD

**Issue by divenyijanos** [onyxfish/csvkit#481]
Is it possible to cancel a request once sent (say, the db is really big, and I forget to add a limit).
`ctrl+C` does not seem to work for me (I use OSX). Thanks in advance.

**Comment by stucka** [comment]
OSX, you should be able to use the built-in job control functions.
Control-Z to suspend it
kill %1      to kill the first job
bg    to have it run in the background
fg     to bring it back to the foreground

**Comment by jpmckinney** [comment]
@divenyijanos Can you paste the command you are running?

**Comment by divenyijanos** [comment]
Sorry, the problem lied somewhere in the ssh connection, not doing anything with `csvkit`. Now `ctrl+C` works as expected. Thanks for developing the tool I really like it.
