### ISSUE TITLE
Feature request: Ability to have csvgrep match the whole field

### ISSUE THREAD

**Issue by stucka** [onyxfish/csvkit#485]
I can use csvgrep to find things I want, or exclude things I don't want. However, by not allowing me to match the full field, I may get false positives (e.g., a search on "0" will also get me "10" and "360"). In my current use case, I'm trying to exclude things where there's a 0, and would like to keep any that are 10.

A command-line option could trigger a shift to a regex that looks at ^something$ instead of something.

**Comment by jpmckinney** [comment]
Just put ^ and $ on your regex:

    echo "a\n1\n10" | csvgrep -c 1 -r 1

Output:

```
a
1
10
```

    echo "a\n1\n10" | csvgrep -c 1 -r 1$

Output:

```
a
1
```

**Comment by stucka** [comment]
I'm an idiot. Thanks.
