### ISSUE TITLE
Agate's default char names are different than the old Table class

### ISSUE THREAD

**Issue by onyxfish** [onyxfish/csvkit#501]
Need to see what all this breaks. And update docs. See #432

**Comment by jpmckinney** [comment]
Also, the capital letters require quoting in most SQL databases.

**Comment by onyxfish** [comment]
Hmmm, I'm not 100% married to the letter names if it breaks stuff, though I do like the obviousness of having it work like Excel.

**Comment by jpmckinney** [comment]
What's the difference between this issue and #498?

**Comment by onyxfish** [comment]
You're right, this is really a dupe.
