### ISSUE TITLE
DBF tests fail on Py3.3 because `enum` doesn't exist

### ISSUE THREAD

**Issue by onyxfish** [onyxfish/csvkit#509]

**Comment by onyxfish** [comment]
Strange this isn't failing on Travis...

**Comment by jpmckinney** [comment]
How to reproduce then?

**Comment by onyxfish** [comment]
It appears there is a newer and more modern Python dbf library: [dbfread](http://dbfread.readthedocs.org/en/latest/). I'm going to take it for a spin. The current one has always been a bit of a problem child.

**Comment by onyxfish** [comment]
Confirmed: dbfread is a better library https://github.com/onyxfish/agate-dbf

**Comment by onyxfish** [comment]
Superseded by #523.
