### ISSUE TITLE
csvsql keeps telling me I don't have postgres library

### ISSUE THREAD

**Issue by ddibiase** [onyxfish/csvkit#522]
I'm on OSX and am getting this msg whenever I try to run my csvsql command. Here's the full command I'm using:

    iconv -f latin1 -t UTF-8 +data/dump/${file}.txt |
    csvcut --tabs --not-columns "ibis_client","company" |
    csvsql --db "postgresql:///import_temp" --insert --table $file

Here's the error:

    You don't appear to have the necessary database backend installed for connection string you're trying to use. Available backends include:

    Postgresql: pip install psycopg2
    MySQL:      pip install MySQL-python

    For details on connection strings and other backends, please see the SQLAlchemy documentation on dialects at: 

    http://www.sqlalchemy.org/docs/dialects/

It keeps repeating that message (likely for every row that's being created).

I do have psycopg2 installed correctly. I use Python and pip as installed via Homebrew (easier for me to manage). At first I thought this was an issue finding the correct library paths but everything is linked correctly (as far as I can tell). If I which pip and python both are running from /usr/local/bin.

I'm also using Postgres.app which is running from the default port.

There doesn't seem to be any other issues regarding this, wondering if it's something I'm doing wrong :-/

**Comment by jpmckinney** [comment]
Is it possible that csvkit is installed system-wide, but psycop2 is installed in a virtualenv, or vice-versa?

Related #467

**Comment by ddibiase** [comment]
How would I be able to quickly determine that? I just tried uninstalling both libraries system-wide (as sudo) and reinstalling them as my local user. Still getting the same issue unfortunately :-/

**Comment by jpmckinney** [comment]
I have them working together inside a virtualenv. If you use a virtualenv, you may need to uninstall them system-wide so that the virtualenv doesn't use the system versions.

**Comment by elfring** [comment]
Should both system configurations work also for advanced data processing together with the software "csvkit"?

**Comment by jpmckinney** [comment]
@elfring Using a virtualenv is a best practice and solves a lot of problems encountered when installing things system-wide.

**Comment by ddibiase** [comment]
Oh man this is so stressful, so I have virtualenv properly setup. Here are the steps I took:

    sudo pip install virtualenv
    virtualenv myenv
    source myenv/bin/activate
    pip install csvkit
    pip install psycopg2

The only weird thing is when I install virtualenv I'm getting:

    The directory '/Users/ddibiase-mbp/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/Users/ddibiase-mbp/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

**Comment by jpmckinney** [comment]
The error comes from SQLAlchemy. I'm not sure where it's looking for psycopg2. Is it possible SQLAlchemy needs to be uninstalled system-wide?

Btw, I like using [virtualenvwrapper](http://virtualenvwrapper.readthedocs.org/en/latest/index.html) which adds some handy command-line tools to work with virtualenv.

**Comment by ddibiase** [comment]
Naw, I uninstalled ALL the libraries and worked with the virtualenv and it
still caused trouble.

I ended up working around this by outputting a structure that Postgres COPY
can work with more efficiently. Basically I'm using csvsql to build a
structure for the tables then copying them in.

Still in love csvkit though, it just really sucks that the postgres
importer isn't working as expected for me.

I have a feeling that my approach is faster anyways. COPY is a very
powerful tool and might get me better performance. I don't know how the
csvsql approach for dumping into the db works though. :-/

On Sun, Jan 24, 2016 at 10:02 AM, James McKinney <notifications@github.com>
wrote:

> The error comes from SQLAlchemy. I'm not sure where it's looking for
> psycopg2. Is it possible SQLAlchemy needs to be uninstalled system-wide?
>
> Btw, I like using virtualenvwrapper
> <http://virtualenvwrapper.readthedocs.org/en/latest/index.html> which
> adds some handy command-line tools to work with virtualenv.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/onyxfish/csvkit/issues/522#issuecomment-174306889>.
>

-- 
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by jpmckinney** [comment]
I got some ideas from #287 and #398

If you open a `python` interpreter and run `import psycopg2` is there any error?

Related #467

**Comment by ddibiase** [comment]
Yeah looks like there's something there:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
        from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
    ImportError: dlopen(/usr/local/lib/python2.7/site-packages/psycopg2/_psycopg.so, 2): no suitable image found.  Did find:
        /usr/local/lib/python2.7/site-packages/psycopg2/_psycopg.so: mach-o, but wrong architecture

**Comment by jpmckinney** [comment]
How did you install PostgreSQL? With Homebrew?

**Comment by jpmckinney** [comment]
[This article](http://www.destructuring.net/2013/07/31/trouble-installing-psycopg2-on-osx/) has some suggestions, including:

    ARCHFLAGS="-arch i386" pip install --upgrade psycopg2

**Comment by ddibiase** [comment]
Hmmm, that seems to have worked. Thanks James! Brew should be handling that
for me (or so I assumed). I just tried the import via csvsql vs. Postgres
native COPY and seems like COPY is much more effective. I'm going to stick
with that. 1.2 million rows (lots of columns) chopped up, validated and
imported in 1 minute.

Wow. Incredible.

On Sun, Jan 24, 2016 at 11:27 AM, James McKinney <notifications@github.com>
wrote:

> This article
> <http://www.destructuring.net/2013/07/31/trouble-installing-psycopg2-on-osx/>
> has some suggestions, including:
>
> ARCHFLAGS="-arch i386" pip install --upgrade psycopg2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/onyxfish/csvkit/issues/522#issuecomment-174313369>.
>

-- 
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by jpmckinney** [comment]
Nice! Yeah, COPY is the fastest way to import. I think csvkit may be streaming, which will be slower.

**Comment by agdolla** [comment]
I had the same problem on ubuntu
using pip3 instead of pip solved the problem

**Comment by tomjkidd** [comment]
Just in case it helps someone in the future:
I also had this problem after a `brew install csvkit` for OSX.
Running `/usr/local/Cellar/csvkit/1.0.7/libexec/bin/pip install psycopg2` was needed to make sure that it was actually installed by the version of pip that the actual `csvsq` runs with.

**Comment by jpmckinney** [comment]
@tomjkidd Thanks! I've added a note to the docs.
