### ISSUE TITLE
`==` python-dateutil requirement in setup.py creates ContextualVersionErrors in downstream packages that require both csvkit and python-dateutil

### ISSUE THREAD

**Issue by palewire** [onyxfish/csvkit#528]
Is there any strong reason why there is ``==`` in [the python-dateutil requirement in setup.py](https://github.com/onyxfish/csvkit/blob/master/setup.py#L12)? 

It's not the end of the world, but I administer a downstream package that uses both python-dateutil and csvkit separately. 

When adding both to my ``install_requires`` without any version number indicated I receive the following error during ``setup.py install`` because CSVkit is disallowing the installation of more recent versions of python-dateutil. 

```
ContextualVersionConflict: (python-dateutil 2.4.2 (/home/ben/.virtualenvs/django-calaccess-campaign-browser/lib/python2.7/site-packages), Requirement.parse('python-dateutil==2.2'), set(['csvkit']))
```

**Comment by onyxfish** [comment]
Yes, `dateutil` has broken csvkit at least twice due to regressions in releases. That being said, it's going away entirely as part of the agate migration (which uses [parsedatetime](https://github.com/bear/parsedatetime) instead) so it won't matter soon!

**Comment by palewire** [comment]
interesting. the string parser function is all our application is using python-dateutil for currently, should we also be moving to parsedatetime?

**Comment by onyxfish** [comment]
It's not a perfect solution, but it is much less of a black box than dateutil. In particular, the test coverage is thorough and straightforward, so I feel pretty comfortable I could fix a showstopper bug in it if I needed to.

**Comment by palewire** [comment]
Yeah we probably should do that.

**Comment by onyxfish** [comment]
I looked [at dateutil's code](https://github.com/dateutil/dateutil/blob/master/dateutil/parser.py) once and almost wrote fell into the pit of writing something else myself, so I was pretty happy when I found parsedatetime.
