### ISSUE TITLE
Ideas for documentation improvements

### ISSUE THREAD

**Issue by jpmckinney** [onyxfish/csvkit#529]
* [x] Move developer-specific installation under "Contributing to csvkit"
* [x] Move remaining installation content to a new "Tips and Troubleshooting" section
* [x] Move "Tips & Tricks" up one level and rename to "Tips and Troubleshooting", eliminate "Appendices" menu item and just have "Arguments common to all utilities" 
* [x] Rename "Command-Line Usage" to "Usage"

**Comment by onyxfish** [comment]
:+1: I'm good with all of these changes.
