### ISSUE TITLE
csvjson: restore streaming for NDJSON

### ISSUE THREAD

**Issue by jpmckinney** [onyxfish/csvkit#553]
May need to revert part of e88f54bb00c049befbc87be7ab625781192b068b

I feel there must be some way to have less code though.

~~If we stay with buffering, then we should implement `--snifflimit` and `--no-inference`.~~

**Comment by onyxfish** [comment]
Honestly, I don't feel that strongly about streaming output for `csvjson`. It can't be read as a streaming format anyway (unless its ND-delimited), so I don't know what the use case would be.

**Comment by onyxfish** [comment]
That being said, it would be nice not to buffer the file. I suppose this is one case where performance is relevant.

**Comment by jpmckinney** [comment]
Yeah, my main reason for using NDJSON is when I have too much data to load into memory, so streaming that would be good.

**Comment by jpmckinney** [comment]
>If we stay with buffering, then we should implement --snifflimit and --no-inference.

We already got this for free.

**Comment by jpmckinney** [comment]
(After some confusion between in2csv and csvjson) implement --snifflimit and --no-inference #568
