### ISSUE TITLE
documentation note on " or ' characters

### ISSUE THREAD

**Issue by SinanGabel** [onyxfish/csvkit#560]
Hi!

For use on Linux I recommend to interchange " and ' characters some places in the documentation: E.g. change: 

FROM:
`sql2csv --db sqlite:///leso.db --query "select * from joined where county='DOUGLAS';" > douglas.csv`

TO:
`v --db sqlite:///leso.db --query 'select * from joined where county="DOUGLAS";' > douglas.csv`

The reason for this is If e.g. the column name was `<county>` instead of `county` in the above FROM example then `'<county>'` will not work while `"<county>"` will work as in the TO example above.

Best,
Sinan

**Comment by jpmckinney** [comment]
Hmm, but in the strict SQL standard as implemented by PostgreSQL and some others, only single quotes are used for strings. Using double quotes for strings would produce an error in those databases. So, I think you're stuck using double quotes around the query, and escaping double quotes around column names.
