### ISSUE TITLE
csvstat and u'\xd6' character

### ISSUE THREAD

**Issue by aborruso** [onyxfish/csvkit#578]
Hi,
in [this](https://gist.github.com/aborruso/0dd1f52b289c4cd09028) csv file I have  u'\xd6' character (in "Öffentliche Bibliothek").

When I run:

    csvstat csvstat_test.csv > out.txt

I have

    'ascii' codec can't encode character u'\xd6' in position 24: ordinal not in range(128)

Is there some way to "transform" the csv file and avoid the error?

Some notes about my csv file. These are two rows of nearby 14000, I have extracted two of these that have inside these kind of characters.
I'm using csvkit 0.9.1.

Thank you

**Comment by jpmckinney** [comment]
I don't get that error on the unreleased version of csvkit. You can install it with:

    pip install -e git+git://github.com/onyxfish/csvkit.git@master#egg=csvkit

**Comment by aborruso** [comment]
Hi @jpmckinney I have just updated to 1.0.0, and I have the same result.

If I run

    csvstat csvstat_test.csv > out.txt

I have 

    'ascii' codec can't encode character u'\xd6' in position 31: ordinal not in range(128)

Thank you

**Comment by jpmckinney** [comment]
The file I downloaded from that gist doesn't produce any error. Can you download and try with that file? It's possible GitHub is changing the encoding such that it's not the same as your local file.

**Comment by aborruso** [comment]
Hi @jpmckinney ,
with 

     curl -s "https://gist.githubusercontent.com/aborruso/0dd1f52b289c4cd09028/raw/025f24b228da602e1eefa4ed0ead160d3dcc7708/csvstat_test.csv" | csvstat > out.txt

I have always the same error. Could it be for the Python version?

I have "sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0)".

Thank you

![2016-02-15_08h46_40](https://cloud.githubusercontent.com/assets/30607/13042472/be25b48c-d3c0-11e5-8b90-0ed84fe82688.png)

**Comment by aborruso** [comment]
@jpmckinney it could be related to [this kind](http://www.azavea.com/blogs/labs/2014/03/solving-unicode-problems-in-python-2-7/) of python 2 problem, but I'm not able to apply the solution to csvkit.

Thank you

**Comment by jpmckinney** [comment]
Ah, yes, this may be related to #574

**Comment by jpmckinney** [comment]
I just committed a fix for #574. Please reinstall csvkit and let me know if the error still occurs:

    pip install -e git+git://github.com/onyxfish/csvkit.git@master#egg=csvkit

**Comment by aborruso** [comment]
Thank you @jpmckinney but unfortunately I have the same error.

**Comment by jpmckinney** [comment]
Weird. If you remove the `> out` then it runs:

     curl -s "https://gist.githubusercontent.com/aborruso/0dd1f52b289c4cd09028/raw/025f24b228da602e1eefa4ed0ead160d3dcc7708/csvstat_test.csv" | csvstat > out.txt

**Comment by jpmckinney** [comment]
I found the solution. I can no longer reproduce the issue with `> out`. Please let me know if there's still a problem after reinstalling.

**Comment by aborruso** [comment]
Wow it works!!!!

I'm very happy to be in some way useful to this very great project

**Comment by jpmckinney** [comment]
Thanks for reporting the issue, @aborruso ! One less bug :)
