### ISSUE TITLE
Add mixed-type column warnings to csvclean

### ISSUE THREAD

**Issue by onyxfish** [onyxfish/csvkit#8]

**Comment by jpmckinney** [comment]
I don't think agate issues such warnings - but I'm not sure I'd implement this anyhow (e.g. if a column is a mix of integers and strings, then maybe we were wrong to guess integers).

**Comment by onyxfish** [comment]
I'm not sure how feasible this is, but it is something that would be useful. It def couldn't be done with the agate type guesser (which always returns the "best guess," so it will never fail). Honestly as much as I've wrangled with type guessing, I don't know there is any sane way to reliably tell some types apart. Closing as "wishful thinking." If anybody has a great idea how to accomplish it they can reopen.
